apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aegismind-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  rules:
    - host: aegismind.sre.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aegismind-service
                port:
                  number: 80
